### ISSUE TITLE
ATF did not work

### ISSUE THREAD

**Issue by Hanwei233** [AlmostReliable/attributetooltipfix#3]
### Minecraft Version

1.20.1

### Mod Version

2.0.1

### Describe the bug!

I used kubejs to modify the weapon's attribute, but ATF didn't work, I think it's a bug
Video:

https://github.com/user-attachments/assets/94ce9257-a06a-49c2-8f7c-9d591a0d60f9

My KJS codes:
```javascript
ItemEvents.modification(event => {
    event.modify("minecraft:netherite_sword", item => {
        item.removeAttribute("minecraft:generic.attack_damage", UUID.fromString("cb3f55d3-645c-4f38-a497-9c13a33db5cf"))
        //item.removeAttribute("minecraft:generic.attack_speed", UUID.fromString("fa233e1c-4180-4865-b01b-bcce9785aca3"))
        item.addAttribute("minecraft:generic.attack_damage", UUID.fromString("cb3f55d3-645c-4f38-a497-9c13a33db5cf"), "Weapon modifier", 10, "addition")
        //item.addAttribute("minecraft:generic.attack_speed", UUID.fromString("fa233e1c-4180-4865-b01b-bcce9785aca3"), "Weapon modifier", -1, "addition")
    })
})
```

### Log

https://gist.github.com/hanweiyyds/8a3db9c70a4209287e53c5ad8640b479

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Thats because ATF does not handle changing the static attributes of items. I can't detect that people changing them. You have to use the correct UUID objects. 

You can load <https://github.com/AlmostReliable/attributetooltipfix/blob/1.20.1/Common/src/main/java/com/almostreliable/attributetooltipfix/ItemModifiers.java> in kubejs and use the UUIDs there.

```js
const ItemModifiers = Java.loadClass("com.almostreliable.attributetooltipfix.ItemModifiers")
// ItemModifiers.damage() or ItemModifiers.speed()
```

<blockquote><img src="https://opengraph.githubassets.com/bb3ac743bafcea2bf34beebd05c31156da51c459e62e4734b3f64779fe7d5c2a/AlmostReliable/attributetooltipfix" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/attributetooltipfix/blob/1.20.1/Common/src/main/java/com/almostreliable/attributetooltipfix/ItemModifiers.java">attributetooltipfix/Common/src/main/java/com/almostreliable/attributetooltipfix/ItemModifiers.java at 1.20.1 · AlmostReliable/attributetooltipfix</a></strong></div><div>A Minecraft mod to fix tooltip rendering for attributes when they are loaded through NBT. - AlmostReliable/attributetooltipfix</div></blockquote>
